### Exploratory Data Analysis: Healthcare Data

- bronze_patient
- bronze_patient_encounter

##### Hypothesis: Patients readmitted within 30 days of being treated and discharged, readmittance is not directly related to previous treatment received.

In [15]:
# import libraries
import pandas as pd
import numpy as np
# import pymysql
from dotenv import load_dotenv
import os
from sqlalchemy import create_engine

import matplotlib.pyplot as plt
import plotly.express as px
import seaborn as sns

# setting to show all columns of data frames
pd.set_option('display.max_columns', None)

In [2]:
# load .env; loads credentials into memeory 
load_dotenv(override=True)

True

In [3]:
host=os.getenv('DB_HOST')
user=os.getenv('DB_USER')
password=os.getenv('DB_PASSWORD')
database=os.getenv('DB_NAME')

In [4]:
# select data from admission_source table
connection_string = f"mysql+pymysql://{user}:{password}@{host}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        admission_source_df = pd.read_sql('''SELECT * FROM admission_source;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from admission_source table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


admission_source_df.head()

   admission_source_id                    admission_source_description
0                    1                              Physician Referral
1                    2                                 Clinic Referral
2                    3                                    HMO Referral
3                    4                        Transfer from a hospital
4                    5  Transfer from a Skilled Nursing Facility (SNF)

In [5]:
admission_source_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 26 entries, 0 to 25
Data columns (total 2 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   admission_source_id           26 non-null     int64
 1   admission_source_description  26 non-null     str
dtypes: int64(1), str(1)
memory usage: 1.1 KB

In [6]:
# select data from admission_type table
connection_string = f"mysql+pymysql://{user}:{password}@{host}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        admission_type_df = pd.read_sql('''SELECT * FROM admission_type;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from admission_type table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


admission_type_df.head()

   admission_type_id admission_type_description
0                  1                  Emergency
1                  2                     Urgent
2                  3                   Elective
3                  4                    Newborn
4                  5              Not Available

In [7]:
admission_type_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 2 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   admission_type_id           8 non-null      int64
 1   admission_type_description  8 non-null      str
dtypes: int64(1), str(1)
memory usage: 338.0 bytes

In [8]:
# select data from discharge_disposition table
connection_string = f"mysql+pymysql://{user}:{password}@{host}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        discharge_disposition_df = pd.read_sql('''SELECT * FROM discharge_disposition;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from discharge_disposition table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


discharge_disposition_df.head()

   discharge_disposition_id                  discharge_disposition_description
0                         1                                 Discharged to home
1                         2  Discharged/transferred to another short term h...
2                         3                      Discharged/transferred to SNF
3                         4                      Discharged/transferred to ICF
4                         5  Discharged/transferred to another type of inpa...

In [9]:
discharge_disposition_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   discharge_disposition_id           30 non-null     int64
 1   discharge_disposition_description  30 non-null     str
dtypes: int64(1), str(1)
memory usage: 2.0 KB

In [10]:
# select data from icd9 table
connection_string = f"mysql+pymysql://{user}:{password}@{host}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        icd9_df = pd.read_sql('''SELECT * FROM icd9;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from icd9 table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


icd9_df.head()

,id,code_start_str,code_end_str,code_start_int,code_end_int,icd9_description
0,1,NaN,NaN,1.0,139.0,INFECTIOUS AND PARASITIC DISEASES (001-139)
1,2,NaN,NaN,140.0,239.0,NEOPLASMS (140-239)
2,3,NaN,NaN,240.0,279.0,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,..."
3,4,NaN,NaN,280.0,289.0,DISEASES OF THE BLOOD AND BLOOD-FORMING ORGANS...
4,5,NaN,NaN,290.0,319.0,"MENTAL, BEHAVIORAL AND NEURODEVELOPMENTAL DISO..."

In [11]:
icd9_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 19 entries, 0 to 18
Data columns (total 6 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                19 non-null     int64
 1   code_start_str    2 non-null      str
 2   code_end_str      2 non-null      str
 3   code_start_int    17 non-null     float64
 4   code_end_int      17 non-null     float64
 5   icd9_description  19 non-null     str
dtypes: float64(2), int64(1), str(3)
memory usage: 2.1 KB

In [12]:
# select data from patient table
connection_string = f"mysql+pymysql://{user}:{password}@{host}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        patient = pd.read_sql('''SELECT * FROM patient;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error selecting data from patient table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


patient.head()

,patient_nbr,race,gender,age,weight,created_date,last_modified
0,135,Caucasian,Female,50-60,Not Captured,2026-05-04 19:13:04,2026-05-04 19:13:04
1,378,Caucasian,Female,50-60,Not Captured,2026-05-04 19:13:04,2026-05-04 19:13:04
2,729,Caucasian,Female,80-90,Not Captured,2026-05-04 19:13:04,2026-05-04 19:13:04
3,774,Caucasian,Female,80-90,Not Captured,2026-05-04 19:13:04,2026-05-04 19:13:04
4,927,African American,Female,30-40,Not Captured,2026-05-04 19:13:04,2026-05-04 19:13:04

In [13]:
patient.info()

<class 'pandas.DataFrame'>
RangeIndex: 71518 entries, 0 to 71517
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   patient_nbr    71518 non-null  int64
 1   race           71518 non-null  str
 2   gender         71518 non-null  str
 3   age            71518 non-null  str
 4   weight         71518 non-null  str
 5   created_date   71518 non-null  datetime64[us]
 6   last_modified  71518 non-null  datetime64[us]
dtypes: datetime64[us](2), int64(1), str(4)
memory usage: 6.0 MB

In [14]:
# select records from the patient_encouonter table
connection_string = f"mysql+pymysql://{user}:{password}@{host}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        patient_encounter = pd.read_sql('''SELECT patient_nbr,encounter_id
                                            ,admission_type_id
                                            ,admission_source_id
                                            ,discharge_disposition_id
                                            ,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures
                                            ,num_medications,number_outpatient,number_emergency,number_inpatient
                                            ,pe.diag_1,icd9_1.icd9_description AS diag_1_desc
                                            ,pe.diag_2,icd9_2.icd9_description AS diag_2_desc
                                            ,pe.diag_3,icd9_3.icd9_description AS diag_3_desc
                                            ,number_diagnoses
                                            ,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,acetohexamide
                                            ,glimepiride,glipizide,glyburide,tolbutamide,tolazamide,examide,pioglitazone,rosiglitazone
                                            ,troglitazone,acarbose,miglitol,citoglipton,insulin,glyburideMetformin,glipizideMetformin
                                            ,glimepiridePioglitazone,metforminRosiglitazone,metforminPioglitazone
                                            ,change_in_meds,diabetesMed,readmitted
                                            FROM patient_encounter pe
                                            INNER JOIN icd9 icd9_1
                                                ON pe.diag_1 BETWEEN icd9_1.code_start_int AND icd9_1.code_end_int
                                                    OR pe.diag_1 BETWEEN icd9_1.code_start_str AND icd9_1.code_end_str
                                            INNER JOIN icd9 AS icd9_2
                                                ON pe.diag_2 BETWEEN icd9_2.code_start_int AND icd9_2.code_end_int
                                                    OR pe.diag_2 BETWEEN icd9_2.code_start_str AND icd9_2.code_end_str
                                            INNER JOIN icd9 AS icd9_3
                                                ON pe.diag_3 BETWEEN icd9_3.code_start_int AND icd9_3.code_end_int
                                                    OR pe.diag_3 BETWEEN icd9_3.code_start_str AND icd9_3.code_end_str
                                        ;''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error select data from patient_encounter table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


patient_encounter.head()

,patient_nbr,encounter_id,admission_type_id,admission_source_id,discharge_disposition_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,...,citoglipton,insulin,glyburideMetformin,glipizideMetformin,glimepiridePioglitazone,metforminRosiglitazone,metforminPioglitazone,change_in_meds,diabetesMed,readmitted
0,55629189,149190,1,7,1,3,Not Captured,Not Captured,59,0,...,No,Up,No,No,No,No,No,Change,Yes,>30
1,42519267,16680,1,7,1,1,Not Captured,Not Captured,51,0,...,No,Steady,No,No,No,No,No,Change,Yes,No
2,82637451,35754,2,2,1,3,Not Captured,Not Captured,31,6,...,No,Steady,No,No,No,No,No,No Change,Yes,>30
3,114882984,63768,1,7,1,5,Not Captured,Not Captured,73,0,...,No,No,No,No,No,No,No,No Change,Yes,>30
4,48330783,12522,2,4,1,13,Not Captured,Not Captured,68,2,...,No,Steady,No,No,No,No,No,Change,Yes,No

In [18]:
patient_encounter.tail(3)

,patient_nbr,encounter_id,admission_type_id,admission_source_id,discharge_disposition_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_1_desc,diag_2,diag_2_desc,diag_3,diag_3_desc,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,acetohexamide,glimepiride,glipizide,glyburide,tolbutamide,tolazamide,examide,pioglitazone,rosiglitazone,troglitazone,acarbose,miglitol,citoglipton,insulin,glyburideMetformin,glipizideMetformin,glimepiridePioglitazone,metforminRosiglitazone,metforminPioglitazone,change_in_meds,diabetesMed,readmitted
101763,126011606,442687568,1,7,1,3,MC,Radiologist,44,2,19,0,0,0,427,DISEASES OF THE CIRCULATORY SYSTEM (390-459),414,DISEASES OF THE CIRCULATORY SYSTEM (390-459),V45,SUPPLEMENTARY CLASSIFICATION OF FACTORS INFLUE...,9,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No Change,Yes,No
101764,125535857,443191964,1,7,1,3,Not Captured,Not Captured,44,0,10,0,0,0,250.13,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",287,DISEASES OF THE BLOOD AND BLOOD-FORMING ORGANS...,E849,SUPPLEMENTARYCLASSIFICATION OF EXTERNAL CAUSES...,7,None,>8,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Change,Yes,No
101765,141379232,443197808,1,7,3,5,CP,Not Captured,39,2,28,0,0,0,823,INJURY AND POISONING (800-999),891,INJURY AND POISONING (800-999),E818,SUPPLEMENTARYCLASSIFICATION OF EXTERNAL CAUSES...,7,None,None,Steady,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Change,Yes,No

In [19]:
patient_encounter.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 49 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   patient_nbr               101766 non-null  int64
 1   encounter_id              101766 non-null  int64
 2   admission_type_id         101766 non-null  int64
 3   admission_source_id       101766 non-null  int64
 4   discharge_disposition_id  101766 non-null  int64
 5   time_in_hospital          101766 non-null  int64
 6   payer_code                101766 non-null  str
 7   medical_specialty         101766 non-null  str
 8   num_lab_procedures        101766 non-null  int64
 9   num_procedures            101766 non-null  int64
 10  num_medications           101766 non-null  int64
 11  number_outpatient         101766 non-null  int64
 12  number_emergency          101766 non-null  int64
 13  number_inpatient          101766 non-null  int64
 14  diag_1                    101766 non-null  str
 15  diag_1_desc               101766 non-null  str
 16  diag_2                    101766 non-null  str
 17  diag_2_desc               101766 non-null  str
 18  diag_3                    101766 non-null  str
 19  diag_3_desc               101766 non-null  str
 20  number_diagnoses          101766 non-null  int64
 21  max_glu_serum             101766 non-null  str
 22  A1Cresult                 101766 non-null  str
 23  metformin                 101766 non-null  str
 24  repaglinide               101766 non-null  str
 25  nateglinide               101766 non-null  str
 26  chlorpropamide            101766 non-null  str
 27  acetohexamide             101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  glipizide                 101766 non-null  str
 30  glyburide                 101766 non-null  str
 31  tolbutamide               101766 non-null  str
 32  tolazamide                101766 non-null  str
 33  examide                   101766 non-null  str
 34  pioglitazone              101766 non-null  str
 35  rosiglitazone             101766 non-null  str
 36  troglitazone              101766 non-null  str
 37  acarbose                  101766 non-null  str
 38  miglitol                  101766 non-null  str
 39  citoglipton               101766 non-null  str
 40  insulin                   101766 non-null  str
 41  glyburideMetformin        101766 non-null  str
 42  glipizideMetformin        101766 non-null  str
 43  glimepiridePioglitazone   101766 non-null  str
 44  metforminRosiglitazone    101766 non-null  str
 45  metforminPioglitazone     101766 non-null  str
 46  change_in_meds            101766 non-null  str
 47  diabetesMed               101766 non-null  str
 48  readmitted                101766 non-null  str
dtypes: int64(13), str(36)
memory usage: 63.5 MB

In [20]:
# merge admission_source and patient_encounter
patient_encounter_df = pd.merge(patient_encounter, admission_source_df, on='admission_source_id', how='inner')

In [21]:
# merge admission_type and patient_encounter
patient_encounter_df = pd.merge(patient_encounter_df, admission_type_df, on='admission_type_id', how='inner')

In [22]:
# merge discharge_disposition_df and patient_encounter
patient_encounter_df = pd.merge(patient_encounter_df, discharge_disposition_df, on='discharge_disposition_id', how='inner')

In [23]:
patient_encounter_df.head(3)
# patient_encounter_df.info()

,patient_nbr,encounter_id,admission_type_id,admission_source_id,discharge_disposition_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,diag_1_desc,diag_2,diag_2_desc,diag_3,diag_3_desc,number_diagnoses,max_glu_serum,A1Cresult,metformin,repaglinide,nateglinide,chlorpropamide,acetohexamide,glimepiride,glipizide,glyburide,tolbutamide,tolazamide,examide,pioglitazone,rosiglitazone,troglitazone,acarbose,miglitol,citoglipton,insulin,glyburideMetformin,glipizideMetformin,glimepiridePioglitazone,metforminRosiglitazone,metforminPioglitazone,change_in_meds,diabetesMed,readmitted,admission_source_description,admission_type_description,discharge_disposition_description
0,55629189,149190,1,7,1,3,Not Captured,Not Captured,59,0,18,0,0,0,276,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",250.01,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",255,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Up,No,No,No,No,No,Change,Yes,>30,Emergency Room,Emergency,Discharged to home
1,42519267,16680,1,7,1,1,Not Captured,Not Captured,51,0,8,0,0,0,197,NEOPLASMS (140-239),157,NEOPLASMS (140-239),250,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",5,None,None,No,No,No,No,No,No,Steady,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,Change,Yes,No,Emergency Room,Emergency,Discharged to home
2,82637451,35754,2,2,1,3,Not Captured,Not Captured,31,6,16,0,0,0,414,DISEASES OF THE CIRCULATORY SYSTEM (390-459),411,DISEASES OF THE CIRCULATORY SYSTEM (390-459),250,"ENDOCRINE, NUTRITIONAL AND METABOLIC DISEASES,...",9,None,None,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,No,Steady,No,No,No,No,No,No Change,Yes,>30,Clinic Referral,Urgent,Discharged to home

In [25]:
# merge patient and patient_encounter
patient_all_df = pd.merge(patient, patient_encounter_df, on='patient_nbr', how='inner')

In [28]:
# veiw all merged patient info
patient_all_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 58 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   patient_nbr                        101766 non-null  int64
 1   race                               101766 non-null  category
 2   gender                             101766 non-null  category
 3   age                                101766 non-null  str
 4   weight                             101766 non-null  str
 5   created_date                       101766 non-null  datetime64[us]
 6   last_modified                      101766 non-null  datetime64[us]
 7   encounter_id                       101766 non-null  int64
 8   admission_type_id                  101766 non-null  int64
 9   admission_source_id                101766 non-null  int64
 10  discharge_disposition_id           101766 non-null  int64
 11  time_in_hospital                   101766 non-null  int64
 12  payer_code                         101766 non-null  str
 13  medical_specialty                  101766 non-null  str
 14  num_lab_procedures                 101766 non-null  int64
 15  num_procedures                     101766 non-null  int64
 16  num_medications                    101766 non-null  int64
 17  number_outpatient                  101766 non-null  int64
 18  number_emergency                   101766 non-null  int64
 19  number_inpatient                   101766 non-null  int64
 20  diag_1                             101766 non-null  str
 21  diag_1_desc                        101766 non-null  str
 22  diag_2                             101766 non-null  str
 23  diag_2_desc                        101766 non-null  str
 24  diag_3                             101766 non-null  str
 25  diag_3_desc                        101766 non-null  str
 26  number_diagnoses                   101766 non-null  int64
 27  max_glu_serum                      101766 non-null  str
 28  A1Cresult                          101766 non-null  str
 29  metformin                          101766 non-null  str
 30  repaglinide                        101766 non-null  str
 31  nateglinide                        101766 non-null  str
 32  chlorpropamide                     101766 non-null  str
 33  acetohexamide                      101766 non-null  str
 34  glimepiride                        101766 non-null  str
 35  glipizide                          101766 non-null  str
 36  glyburide                          101766 non-null  str
 37  tolbutamide                        101766 non-null  str
 38  tolazamide                         101766 non-null  str
 39  examide                            101766 non-null  str
 40  pioglitazone                       101766 non-null  str
 41  rosiglitazone                      101766 non-null  str
 42  troglitazone                       101766 non-null  str
 43  acarbose                           101766 non-null  str
 44  miglitol                           101766 non-null  str
 45  citoglipton                        101766 non-null  str
 46  insulin                            101766 non-null  str
 47  glyburideMetformin                 101766 non-null  str
 48  glipizideMetformin                 101766 non-null  str
 49  glimepiridePioglitazone            101766 non-null  str
 50  metforminRosiglitazone             101766 non-null  str
 51  metforminPioglitazone              101766 non-null  str
 52  change_in_meds                     101766 non-null  str
 53  diabetesMed                        101766 non-null  str
 54  readmitted                         101766 non-null  str
 55  admission_source_description       101766 non-null  str
 56  admission_type_description         101766 non-null  str
 57  discharge_disposition_description  101766 non-null  str
dtypes: category(2), datetime64[us](2), int64(13), str(41)
memory usage: 76.2 MB

In [27]:
# change datatype 
patient_all_df['race'] = patient_all_df['race'].astype('category')
patient_all_df['gender'] = patient_all_df['gender'].astype('category')

In [29]:
# descriptive statistics on numeric data only
patient_all_df.describe(include=[np.number])

,patient_nbr,encounter_id,admission_type_id,admission_source_id,discharge_disposition_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,1.017660e+05,1.017660e+05,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,5.433040e+07,1.652016e+08,2.024006,5.754437,3.715642,4.395987,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,3.869636e+07,1.026403e+08,1.445403,4.064081,5.280166,2.985108,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.350000e+02,1.252200e+04,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,2.341322e+07,8.496119e+07,1.000000,1.000000,1.000000,2.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,4.550514e+07,1.523890e+08,1.000000,7.000000,1.000000,4.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,8.754595e+07,2.302709e+08,3.000000,7.000000,4.000000,6.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,1.895026e+08,4.438672e+08,8.000000,25.000000,28.000000,14.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [160]:
# descriptive statistics on subset (specific numeric columns) ; 'admission_type_id', 
patient_all_df[['admission_source_id', 'discharge_disposition_id','num_lab_procedures'
                ,'num_procedures','num_medications', 'number_outpatient', 'number_emergency'
                ,'number_inpatient','number_diagnoses']].describe()

,admission_source_id,discharge_disposition_id,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000,101766.000000
mean,5.754437,3.715642,43.095641,1.339730,16.021844,0.369357,0.197836,0.635566,7.422607
std,4.064081,5.280166,19.674362,1.705807,8.127566,1.267265,0.930472,1.262863,1.933600
min,1.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000
25%,1.000000,1.000000,31.000000,0.000000,10.000000,0.000000,0.000000,0.000000,6.000000
50%,7.000000,1.000000,44.000000,1.000000,15.000000,0.000000,0.000000,0.000000,8.000000
75%,7.000000,4.000000,57.000000,2.000000,20.000000,0.000000,0.000000,1.000000,9.000000
max,25.000000,28.000000,132.000000,6.000000,81.000000,42.000000,76.000000,21.000000,16.000000

In [162]:
# visualize ;'admission_type_id', 
# patient_all_df[['admission_source_id', 'discharge_disposition_id','num_lab_procedures'
#                 ,'num_procedures','num_medications', 'number_outpatient', 'number_emergency'
#                 ,'number_inpatient','number_diagnoses']].describe().loc[['mean', 'std', '50%']].plot(kind='bar')

In [161]:
# 'admission_type_id',
fig = px.box(patient_all_df[['admission_source_id', 'discharge_disposition_id','num_lab_procedures'
                ,'num_procedures','num_medications', 'number_outpatient', 'number_emergency'
                ,'number_inpatient','number_diagnoses']].describe().loc[['mean', 'max', 'min','std', '50%']]
                , title='Descriptive Statistics: All Patient Data')

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [45]:
# perform analysis

# patient per admission types (Why) : represents the priority and nature of the patient's arrival, often used for scheduling and administrative analysis.
patient_admission_type = patient_all_df.groupby('admission_type_description')['patient_nbr'].count().sort_values(ascending=False).reset_index()
patient_admission_type

  admission_type_description  patient_nbr
0                  Emergency        53990
1                   Elective        18869
2                     Urgent        18480
3               Not Selected         5291
4              Not Available         4785
5                 Not Mapped          320
6              Trauma Center           21
7                    Newborn           10

In [42]:
# top 3
df_3 = patient_admission_type.head(3)
fig = px.bar(df_3, x = 'admission_type_description'
             ,y='patient_nbr', title='Admission Types Distribution'
             , color='admission_type_description'
             , labels={'patient_nbr': 'patients', 'admission_type_description': 'descriptions'})
fig.update_layout(showlegend=False)
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [154]:
# patient per admission source : (Where) - identifies the location or context of the patient immediately prior to being admitted to the facility
# patient_admission_source = patient_all_df.groupby('admission_source_description')['patient_nbr'].count().sort_values(ascending=False).reset_index()
# patient_admission_source = patient_all_df.groupby('admission_source_description').agg({
#     'patient_nbr': 'count',
#     'time_in_hospital': ['sum', 'mean']
#     }).sort_values(by=('patient_nbr','count'), ascending=False)
# patient_admission_source = patient_admission_source.reset_index()

patient_admission_source = patient_all_df.groupby('admission_source_description').agg({
    'patient_nbr': 'count',
    'time_in_hospital': 'mean',
    }).sort_values('patient_nbr', ascending=False)
patient_admission_source = patient_admission_source.reset_index()
patient_admission_source

,admission_source_description,patient_nbr,time_in_hospital
0,Emergency Room,57494,4.387519
1,Physician Referral,29565,4.257805
2,Not Selected,6781,4.155729
3,Transfer from a hospital,3187,5.814559
4,Transfer from another health care facility,2264,4.426237
5,Clinic Referral,1104,4.684783
6,Transfer from a Skilled Nursing Facility (SNF),855,5.829240
7,HMO Referral,187,4.823529
8,Not Mapped,161,4.577640
9,Not Available,125,3.416000
10,Court/Law Enforcement,16,5.562500
11,Transfer from hospital inpt/same fac reslt in ...,12,10.000000
12,Transfer from critial access hospital,8,4.375000
13,Normal Delivery,2,2.500000
14,Transfer from Ambulatory Surgery Center,2,6.000000
15,Extramural Birth,2,3.000000
16,Sick Baby,1,3.000000

In [148]:
patient_admission_source.columns

Index(['admission_source_description', 'patient_nbr', 'time_in_hospital'], dtype='str')

In [157]:
# visualize
fig = px.bar(patient_admission_source.head(4), x='admission_source_description'
             , y='patient_nbr', color='time_in_hospital'
             , barmode='group'
             , title='Admission Source Distribution')

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [159]:
# visualize the top 5
df_5 = patient_admission_source.head(4)
fig = px.pie(df_5, values='patient_nbr', names='admission_source_description'
             ,  title='Admission Sources Distribution')
fig.show()

In [53]:
# Patient Diagnosis
# primary_diagnosis = patient_all_df.groupby('diag_1')['patient_nbr'].count().sort_values(ascending=False).reset_index()
# primary_diagnosis
# 716 unique diag_1
# primary_diagnosis = patient_all_df['diag_1']

# for d in range(len(primary_diagnosis)):
#     print(f'diag_1: {primary_diagnosis[d]}')

In [54]:
# Top Ten Primary Diagnosis Codes
connection_string = f"mysql+pymysql://{user}:{password}@{host}/{database}"
try:
    engine = create_engine(connection_string)

    with engine.connect() as conn:
        primary_top_ten_df = pd.read_sql('''WITH patient_primary_diagnosis_cte AS (
                                            SELECT pe.patient_nbr
                                                ,diag_1
                                                ,icd9_1.icd9_description
                                            FROM patient_encounter pe
                                            INNER JOIN icd9 icd9_1
                                                ON pe.diag_1 BETWEEN icd9_1.code_start_int AND 
                                                        icd9_1.code_end_int
                                                    OR pe.diag_1 BETWEEN icd9_1.code_start_str AND 
                                                        icd9_1.code_end_str
                                            )
                                            SELECT diag_1 AS primary_diagnosis
                                                , icd9_description AS description
                                                , COUNT(ppdc.patient_nbr) AS num_of_patients
                                            FROM patient_primary_diagnosis_cte ppdc
                                            GROUP BY diag_1
                                                ,icd9_description
                                            ORDER BY COUNT(ppdc.patient_nbr) DESC 
                                            LIMIT 10;
                                        ''', con = conn)

        conn.close()

except (Exception) as error:
        error_log   = 'Error select data from patient_encounter table. Check system file.'                  
        with open('error_log.txt','w') as error:
           error.write(error_log)


primary_top_ten_df.head(10)

,primary_diagnosis,description,num_of_patients
0,428,DISEASES OF THE CIRCULATORY SYSTEM (390-459),6862
1,414,DISEASES OF THE CIRCULATORY SYSTEM (390-459),6581
2,786,"SYMPTOMS, SIGNS, AND ILL-DEFINED CONDITIONS (7...",4016
3,410,DISEASES OF THE CIRCULATORY SYSTEM (390-459),3614
4,486,DISEASES OF THE RESPIRATORY SYSTEM (460-519),3508
5,427,DISEASES OF THE CIRCULATORY SYSTEM (390-459),2766
6,491,DISEASES OF THE RESPIRATORY SYSTEM (460-519),2275
7,715,DISEASES OF THE MUSCULOSKELETAL SYSTEM AND CON...,2151
8,682,DISEASES OF THE SKIN AND SUBCUTANEOUS TISSUE (...,2042
9,434,DISEASES OF THE CIRCULATORY SYSTEM (390-459),2028

In [55]:
# visualize
fig = px.bar(primary_top_ten_df, x='primary_diagnosis',
             y='num_of_patients', color='num_of_patients'
             , title='Top Ten Primary Diagnosis Codes'
             , hover_data='description')

fig.show()

In [234]:
# patient per discharge disposition types : the final destination or setting a patient goes to upon leaving a healthcare facility,
# determining their next level of care.  It defines whether the patient is going home (with or without support), 
# transferring to another facility (like nursing or rehab), or leaving against medical advice
# patient_discharge_disposition_type = patient_all_df.groupby('discharge_disposition_description')['patient_nbr'].count().sort_values(ascending=False).reset_index()
patient_discharge_disposition_type = patient_all_df.groupby('discharge_disposition_description').agg({
    'patient_nbr': 'count'
}).sort_values(by='patient_nbr', ascending=False)
patient_discharge_disposition_type = patient_discharge_disposition_type.reset_index()
patient_discharge_disposition_type['total_patients'] = patient_discharge_disposition_type['patient_nbr'].sum()
patient_discharge_disposition_type['pct_discharge_disposition'] = ((patient_discharge_disposition_type['patient_nbr'] / patient_discharge_disposition_type['patient_nbr'].sum()) * 100).round(1)
patient_discharge_disposition_type

,discharge_disposition_description,patient_nbr,total_patients,pct_discharge_disposition
0,Discharged to home,60234,101766,59.2
1,Discharged/transferred to SNF,13954,101766,13.7
2,Discharged/transferred to home with home healt...,12902,101766,12.7
3,Not Selected,3691,101766,3.6
4,Discharged/transferred to another short term h...,2128,101766,2.1
5,Discharged/transferred to another rehab fac in...,1993,101766,2.0
6,Expired,1642,101766,1.6
7,Discharged/transferred to another type of inpa...,1184,101766,1.2
8,Not Mapped,989,101766,1.0
9,Discharged/transferred to ICF,815,101766,0.8
10,Left AMA,623,101766,0.6
11,Discharged/transferred to a long term care hos...,412,101766,0.4
12,Hospice / home,399,101766,0.4
13,Hospice / medical facility,372,101766,0.4
14,Discharged/transferred to a federal health car...,139,101766,0.1
15,Discharged/transferred to home under care of H...,108,101766,0.1
16,Discharged/transferred within this institution...,63,101766,0.1
17,Discharged/transferred to a nursing facility c...,48,101766,0.0
18,Admitted as an inpatient to this hospital,21,101766,0.0
19,Discharged/transferred/referred to this instit...,14,101766,0.0
20,Discharged/transferred/referred another instit...,11,101766,0.0
21,"Expired at home. Medicaid only, hospice.",8,101766,0.0
22,Neonate discharged to another hospital for neo...,6,101766,0.0
23,Discharged/transferred to another Type of Heal...,5,101766,0.0
24,Still patient or expected to return for outpat...,3,101766,0.0
25,"Expired in a medical facility. Medicaid only, ...",2,101766,0.0

In [235]:
patient_discharge_disposition_type.columns

Index(['discharge_disposition_description', 'patient_nbr', 'total_patients',
       'pct_discharge_disposition'],
      dtype='str')

In [242]:
# visualize discharge_disposition_description : Top Three
fig = px.bar(patient_discharge_disposition_type.head(3), x='discharge_disposition_description'
             ,y='patient_nbr', hover_data='pct_discharge_disposition', color='discharge_disposition_description'
            ,title='Discharge Disposition Distribution')

fig.update_layout(showlegend=False)
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [56]:
# Distribution of Race and Gender
race_gender_df = patient_all_df.groupby(['race', 'gender'])['patient_nbr'].count().reset_index()
race_gender_df

                race           gender  patient_nbr
0   African American           Female        11733
1   African American             Male         7472
2              Asian           Female          321
3              Asian             Male          322
4          Caucasian           Female        39660
5          Caucasian             Male        36423
6           Hispanic           Female         1074
7           Hispanic             Male          950
8       Not Captured           Female         1150
9       Not Captured             Male         1129
10      Not Captured  Unknown/Invalid            2
11             Other           Female          769
12             Other             Male          760
13             Other  Unknown/Invalid            1

In [57]:
# Top Seven
top_seven = race_gender_df.head(8)
top_seven

               race  gender  patient_nbr
0  African American  Female        11733
1  African American    Male         7472
2             Asian  Female          321
3             Asian    Male          322
4         Caucasian  Female        39660
5         Caucasian    Male        36423
6          Hispanic  Female         1074
7          Hispanic    Male          950

In [59]:
#visualize
fig = px.bar(top_seven, x='gender', y='patient_nbr', color='race'
             , title='Distribution of Race vs Gender')
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [189]:
# Determine the number of readmitted patients and the percentage of total encounters that they represent

readmitted_df = patient_all_df.groupby('readmitted').agg({
    'encounter_id': 'count',
    'patient_nbr': 'nunique'
    }) #.sort_values(by='encounter_id', ascending=False)
readmitted_df = readmitted_df.reset_index()
readmitted_df['total_encounters'] = readmitted_df['encounter_id'].sum()
readmitted_df['percent_encounters'] = ((readmitted_df['encounter_id'] / readmitted_df['total_encounters']) * 100).round(1)
readmitted_df

  readmitted  encounter_id  patient_nbr  total_encounters  percent_encounters
0        <30         11357         8834            101766                11.2
1        >30         35545        24139            101766                34.9
2         No         54864        54820            101766                53.9

In [190]:
# visualize
fig = px.bar(readmitted_df, x='readmitted', y='encounter_id', color='encounter_id'
             , title='Readmittance Encounters'
             , hover_data='percent_encounters')
fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)
fig.show()

In [ ]:
# Identify the age distribution of patients; 10 age groups
age_df = patient_all_df.groupby(['age', 'readmitted'])['patient_nbr'].count().reset_index()
age_df

       age readmitted  patient_nbr
0     0-10        <30            3
1     0-10        >30           25
2     0-10         No          132
3    10-20        <30           37
4    10-20        >30          206
5    10-20         No          427
6    20-30        <30          225
7    20-30        >30          492
8    20-30         No          911
9    30-40        <30          424
10   30-40        >30         1129
11   30-40         No         2164
12   40-50        <30          992
13   40-50        >30         3113
14   40-50         No         5380
15   50-60        <30         1652
16   50-60        >30         5711
17   50-60         No         9671
18   60-70        <30         2456
19   60-70        >30         7838
20   60-70         No        12080
21   70-80        <30         3097
22   70-80        >30         9430
23   70-80         No        13527
24   80-90        <30         2136
25   80-90        >30         6594
26   80-90         No         8897
27  90-100        <30          335
28  90-100        >30         1007
29  90-100         No         1675

In [194]:
# visualize
fig = px.bar(age_df, x='age', y='patient_nbr', color='readmitted', barmode='group'
             , title='Age vs Readmittance')

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()

In [196]:
# 11. Calculate the average number of medications prescribed for patients in each age group and a change in meds per age group
# age_meds_prescribed_and_changed_df = patient_all_df.groupby(['age', 'change_in_meds'])['patient_nbr'].count().reset_index()
age_meds_prescribed_and_changed_df = patient_all_df.groupby(['age', 'change_in_meds']).agg({
    'patient_nbr': 'count',
    'num_medications': 'mean'
    }).reset_index()
age_meds_prescribed_and_changed_df

       age change_in_meds  patient_nbr  num_medications
0     0-10         Change           33         7.090909
1     0-10      No Change          127         5.960630
2    10-20         Change          269         9.085502
3    10-20      No Change          401         7.703242
4    20-30         Change          835        12.920958
5    20-30      No Change          793        10.689786
6    30-40         Change         1749        15.549457
7    30-40      No Change         1968        12.812500
8    40-50         Change         4579        17.252894
9    40-50      No Change         4906        13.530575
10   50-60         Change         8143        18.726022
11   50-60      No Change         8891        14.540547
12   60-70         Change        10865        19.404694
13   60-70      No Change        11509        15.076201
14   70-80         Change        11850        18.652911
15   70-80      No Change        14204        14.600394
16   80-90         Change         7520        17.565559
17   80-90      No Change        10107        13.701395
18  90-100         Change         1168        16.163527
19  90-100      No Change         1849        12.392104

In [199]:
# visualize
fig = px.bar(age_meds_prescribed_and_changed_df, x='age', y='patient_nbr', color='change_in_meds', barmode='group'
             , title='Distribution of Medication Changes / Avg Number of Medications Over Age'
             , hover_data='num_medications')

fig.update_xaxes(showgrid=False)
fig.update_yaxes(showgrid=False)

fig.show()